name: Anga UTM CI

on:
  push:
    branches: [master, develop, initial-model-tests]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: anga_test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
      - uses: nyaruka/postgis-action@v1
        with:
          postgresql version: "10" # See https://hub.docker.com/_/postgres for available versions
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Renaming .env.sample to .env
        run: |
          cp .env.sample .env
      - name: Installing Geodjango
        run: |
          sudo apt-get install binutils libproj-dev gdal-bin
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          py.test --ds=ANGA_UTM.settings.local_testing --nomigrations
